[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "mrov"
name = "WeatherRegistry"
description = "A mod for controlling the game's weather system."
websiteUrl = "https://github.com/AndreyMrovol/LethalWeatherRegistry"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
mrov-MrovLib = "0.3.6"

[build]
icon = "../icon.png"
readme = "../README.md"
outdir = "../WeatherRegistry/dist"

[[build.copy]]
source = "../WeatherRegistry/bin/Release/netstandard2.1/WeatherRegistry.dll"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LICENSE.md"
target = "/"

[[build.copy]]
source = "../Opensource.md"
target = "/"

[publish]
communities = [ "lethal-company", ]