name: curseforge-test

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [main]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  build:
    name: curseforge-test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"

      - name: Install Evaisa's netcode-patcher
        run: |
          dotnet tool install -g Evaisa.NetcodePatcher.Cli

      - name: Restore project
        run: |
          dotnet restore
          dotnet tool restore

      - name: Build solution
        run: |
          dotnet build -c Release

      - name: Set MOD_NAME environment variable
        run: echo "MOD_NAME=$(cat ./*/dist/name.txt )" >> $GITHUB_ENV

      - name: Set MOD_VERSION environment variable
        run: echo "MOD_VERSION=$(cat ./*/dist/version.txt )" >> $GITHUB_ENV

      - name: Set ZIP_PATH environment variable
        run: echo "ZIP_PATH=./*/dist/curseforge.zip" >> $GITHUB_ENV

      - name: "Upload to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_API_KEY }}
          project_id: ${{ secrets.CURSEFORGE_PROJECTID }}
          game_endpoint: "lethal-company"
          game_versions: "0.50.0"
          file_path: ${{ env.ZIP_PATH }}
          display_name: ${{ env.MOD_NAME }} v${{ env.MOD_VERSION }}

      - name: Upload Thunderstore artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: ./*/dist/*.zip
